// ALL models available via Muapi.ai API
// Full registry

export const IMAGE_MODELS = [
  {
    id: 'gpt4o-text-to-image',
    name: 'GPT Image 2',
    provider: 'OpenAI',
    tier: 'premium',
    badge: 'NEW',
    description: '4K images with near-perfect text rendering',
    creditCost: 8,
    type: 'text-to-image',
    endpoint: '/gpt4o-text-to-image',
  },
  {
    id: 'google-imagen4-ultra',
    name: 'Imagen 4 Ultra',
    provider: 'Google',
    tier: 'premium',
    badge: 'NEW',
    description: 'Google flagship — photorealism, rich textures, production-level',
    creditCost: 10,
    type: 'text-to-image',
    endpoint: '/google-imagen4-ultra',
  },
  {
    id: 'google-imagen4-fast',
    name: 'Imagen 4 Fast',
    provider: 'Google',
    tier: 'standard',
    badge: null,
    description: 'Optimized for speed — high quality images in seconds',
    creditCost: 4,
    type: 'text-to-image',
    endpoint: '/google-imagen4-fast',
  },
  {
    id: 'hidream_i1_full_image',
    name: 'HiDream I1 Full',
    provider: 'HiDream',
    tier: 'premium',
    badge: 'TOP',
    description: 'Highest resolution, superior prompt understanding',
    creditCost: 6,
    type: 'text-to-image',
    endpoint: '/hidream_i1_full_image',
  },
  {
    id: 'hidream-fast',
    name: 'HiDream Fast',
    provider: 'HiDream',
    tier: 'standard',
    badge: null,
    description: 'Fast HiDream — balanced speed and quality',
    creditCost: 3,
    type: 'text-to-image',
    endpoint: '/hidream-fast',
  },
  {
    id: 'flux-2-pro',
    name: 'Flux 2 Pro',
    provider: 'Black Forest Labs',
    tier: 'premium',
    badge: null,
    description: 'Professional Flux — best prompt adherence',
    creditCost: 5,
    type: 'text-to-image',
    endpoint: '/flux-2-pro',
  },
  {
    id: 'flux-kontext-max-t2i',
    name: 'Flux Kontext Max',
    provider: 'Black Forest Labs',
    tier: 'premium',
    badge: 'TOP',
    description: 'Reference-faithful editing and style control',
    creditCost: 6,
    type: 'text-to-image',
    endpoint: '/flux-kontext-max-t2i',
  },
  {
    id: 'flux-kontext-dev',
    name: 'Flux Kontext Dev',
    provider: 'Black Forest Labs',
    tier: 'standard',
    badge: null,
    description: 'Kontext development model — fast iteration',
    creditCost: 3,
    type: 'text-to-image',
    endpoint: '/flux-kontext-dev',
  },
  {
    id: 'flux-dev-image',
    name: 'Flux Dev',
    provider: 'Black Forest Labs',
    tier: 'standard',
    badge: null,
    description: 'Creative high-quality image generation',
    creditCost: 2,
    type: 'text-to-image',
    endpoint: '/flux-dev-image',
  },
  {
    id: 'flux-schnell',
    name: 'Flux Schnell',
    provider: 'Black Forest Labs',
    tier: 'fast',
    badge: null,
    description: 'Lightning-fast image generation',
    creditCost: 1,
    type: 'text-to-image',
    endpoint: '/flux-schnell',
  },
  {
    id: 'seedream-5.0',
    name: 'Seedream 5.0',
    provider: 'ByteDance',
    tier: 'premium',
    badge: 'NEW',
    description: 'Intelligent visual reasoning — detailed compositions',
    creditCost: 5,
    type: 'text-to-image',
    endpoint: '/seedream-5.0',
  },
  {
    id: 'hunyuan-image-3.0',
    name: 'Hunyuan Image 3.0',
    provider: 'Tencent',
    tier: 'standard',
    badge: null,
    description: 'Photorealistic portraits, environments and concept art',
    creditCost: 3,
    type: 'text-to-image',
    endpoint: '/hunyuan-image-3.0',
  },
  {
    id: 'nano-banana-pro',
    name: 'Nano Banana Pro',
    provider: 'Muapi',
    tier: 'premium',
    badge: 'TOP',
    description: 'Best 4K image model — ultra-fast pro quality',
    creditCost: 4,
    type: 'text-to-image',
    endpoint: '/nano-banana-pro',
  },
  {
    id: 'nano-banana-2',
    name: 'Nano Banana 2',
    provider: 'Muapi',
    tier: 'standard',
    badge: null,
    description: 'Pro quality at Flash speed',
    creditCost: 2,
    type: 'text-to-image',
    endpoint: '/nano-banana-2',
  },
  {
    id: 'sdxl',
    name: 'SDXL',
    provider: 'Stability AI',
    tier: 'free',
    badge: null,
    description: 'Classic open-source powerhouse — any style',
    creditCost: 1,
    type: 'text-to-image',
    endpoint: '/sdxl',
  },
  {
    id: 'midjourney',
    name: 'Midjourney v7',
    provider: 'Midjourney',
    tier: 'premium',
    badge: 'TOP',
    description: 'Artistic quality benchmark — best-looking outputs',
    creditCost: 7,
    type: 'text-to-image',
    endpoint: '/midjourney',
  },
  {
    id: 'croma-image',
    name: 'Croma Image',
    provider: 'Croma',
    tier: 'standard',
    badge: null,
    description: 'Advanced text-to-image for versatile creative visuals',
    creditCost: 2,
    type: 'text-to-image',
    endpoint: '/croma-image',
  },
  {
    id: 'qwen-image-edit-plus',
    name: 'Qwen Image Edit Plus',
    provider: 'Alibaba',
    tier: 'standard',
    badge: 'NEW',
    description: 'Multi-reference editing — bg swap, style, text, object edits',
    creditCost: 4,
    type: 'image-to-image',
    endpoint: '/qwen-image-edit-plus',
  },
  {
    id: 'ai-image-upscale',
    name: 'AI Upscale',
    provider: 'Muapi',
    tier: 'standard',
    badge: null,
    description: 'AI-powered image upscaling and enhancement',
    creditCost: 2,
    type: 'enhance',
    endpoint: '/ai-image-upscale',
  },
  {
    id: 'topaz-image-upscale',
    name: 'Topaz Upscale',
    provider: 'Topaz',
    tier: 'premium',
    badge: 'TOP',
    description: 'Professional Topaz-grade upscaling',
    creditCost: 4,
    type: 'enhance',
    endpoint: '/topaz-image-upscale',
  },
  {
    id: 'ai-background-remover',
    name: 'Background Remover',
    provider: 'Muapi',
    tier: 'standard',
    badge: null,
    description: 'Clean background removal in one click',
    creditCost: 1,
    type: 'enhance',
    endpoint: '/ai-background-remover',
  },
  {
    id: 'ai-outpaint',
    name: 'AI Outpaint',
    provider: 'Muapi',
    tier: 'standard',
    badge: null,
    description: 'Expand image borders in any direction',
    creditCost: 3,
    type: 'image-to-image',
    endpoint: '/ai-outpaint',
  },
  {
    id: 'ai-colorize',
    name: 'AI Colorize',
    provider: 'Muapi',
    tier: 'standard',
    badge: null,
    description: 'Colorize black-and-white photos automatically',
    creditCost: 2,
    type: 'enhance',
    endpoint: '/ai-colorize',
  },
  {
    id: 'ai-ghibli-style',
    name: 'Studio Ghibli Style',
    provider: 'Muapi',
    tier: 'standard',
    badge: null,
    description: 'Transform any image into Ghibli animation style',
    creditCost: 2,
    type: 'image-to-image',
    endpoint: '/ai-ghibli-style',
  },
  {
    id: 'ai-color-photo',
    name: 'Color Enhancement',
    provider: 'Muapi',
    tier: 'standard',
    badge: null,
    description: 'Professional color correction and enhancement',
    creditCost: 1,
    type: 'enhance',
    endpoint: '/ai-color-photo',
  },
]

export const VIDEO_MODELS = [
  {
    id: 'seedance-v2.0-t2v',
    name: 'Seedance 2.0',
    provider: 'ByteDance',
    tier: 'premium',
    badge: 'TOP',
    description: 'ByteDance flagship — best quality video generation',
    creditCost: 25,
    type: 'text-to-video',
    maxDuration: 15,
    aspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
    endpoint: '/seedance-v2.0-t2v',
  },
  {
    id: 'seedance-v2.0-extend',
    name: 'Seedance 2.0 Extend',
    provider: 'ByteDance',
    tier: 'premium',
    badge: 'EXTEND',
    description: 'Extend an existing Seedance 2.0 video',
    creditCost: 15,
    type: 'text-to-video',
    maxDuration: 10,
    requiresRequestId: true,
    aspectRatios: [],
    endpoint: '/seedance-v2.0-extend',
  },
  {
    id: 'veo3.1-text-to-video',
    name: 'Veo 3.1',
    provider: 'Google',
    tier: 'premium',
    badge: 'NEW',
    description: "Google's highest quality AI video generation",
    creditCost: 40,
    type: 'text-to-video',
    maxDuration: 8,
    aspectRatios: ['16:9', '9:16', '1:1'],
    endpoint: '/veo3.1-text-to-video',
  },
  {
    id: 'kling-v2.6-pro-t2v',
    name: 'Kling 3.0 Pro',
    provider: 'Kuaishou',
    tier: 'premium',
    badge: 'TOP',
    description: 'Industry-leading motion quality and realism',
    creditCost: 30,
    type: 'text-to-video',
    maxDuration: 10,
    aspectRatios: ['16:9', '9:16', '1:1'],
    endpoint: '/kling-v2.6-pro-t2v',
  },
  {
    id: 'wan2.5-text-to-video',
    name: 'WAN 2.5',
    provider: 'Alibaba',
    tier: 'standard',
    badge: null,
    description: 'Fast open-source video generation with great quality',
    creditCost: 12,
    type: 'text-to-video',
    maxDuration: 10,
    aspectRatios: ['16:9', '9:16', '1:1'],
    endpoint: '/wan2.5-text-to-video',
  },
  {
    id: 'hunyuan-text-to-video',
    name: 'Hunyuan Video',
    provider: 'Tencent',
    tier: 'standard',
    badge: null,
    description: 'Tencent cinematic video — high visual quality',
    creditCost: 15,
    type: 'text-to-video',
    maxDuration: 8,
    aspectRatios: ['16:9', '9:16'],
    endpoint: '/hunyuan-text-to-video',
  },
  {
    id: 'minimax-hailuo-02-pro-t2v',
    name: 'MiniMax Hailuo 02 Pro',
    provider: 'MiniMax',
    tier: 'standard',
    badge: null,
    description: 'Full HD multi-aspect video with fast generation',
    creditCost: 15,
    type: 'text-to-video',
    maxDuration: 6,
    aspectRatios: ['16:9', '9:16', '1:1'],
    endpoint: '/minimax-hailuo-02-pro-t2v',
  },
  {
    id: 'grok-imagine-text-to-video',
    name: 'Grok T2V',
    provider: 'xAI',
    tier: 'standard',
    badge: 'NEW',
    description: 'xAI video generation — fun, normal, and spicy modes',
    creditCost: 20,
    type: 'text-to-video',
    maxDuration: 30,
    aspectRatios: ['16:9', '9:16', '1:1'],
    endpoint: '/grok-imagine-text-to-video',
  },
  {
    id: 'seedance-v2.0-i2v',
    name: 'Seedance 2.0 I2V',
    provider: 'ByteDance',
    tier: 'premium',
    badge: 'TOP',
    description: 'Animate any image — best quality I2V',
    creditCost: 20,
    type: 'image-to-video',
    maxDuration: 15,
    aspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
    endpoint: '/seedance-v2.0-i2v',
  },
  {
    id: 'seedance-2.0-new-omni',
    name: 'Seedance 2.0 Omni',
    provider: 'ByteDance',
    tier: 'premium',
    badge: 'NEW',
    description: 'Seamlessly continue any Seedance generation',
    creditCost: 22,
    type: 'image-to-video',
    maxDuration: 15,
    endpoint: '/seedance-2.0-new-omni',
  },
  {
    id: 'kling-v2.6-pro-i2v',
    name: 'Kling 3.0 Pro I2V',
    provider: 'Kuaishou',
    tier: 'premium',
    badge: 'TOP',
    description: 'Animate images with leading motion quality',
    creditCost: 25,
    type: 'image-to-video',
    maxDuration: 10,
    endpoint: '/kling-v2.6-pro-i2v',
  },
  {
    id: 'veo3.1-image-to-video',
    name: 'Veo 3.1 I2V',
    provider: 'Google',
    tier: 'premium',
    badge: 'NEW',
    description: "Google's image animation — 8s cinematic clips",
    creditCost: 35,
    type: 'image-to-video',
    maxDuration: 8,
    endpoint: '/veo3.1-image-to-video',
  },
  {
    id: 'wan2.5-image-to-video',
    name: 'WAN 2.5 I2V',
    provider: 'Alibaba',
    tier: 'standard',
    badge: null,
    description: 'Fast image animation with WAN quality',
    creditCost: 10,
    type: 'image-to-video',
    maxDuration: 10,
    endpoint: '/wan2.5-image-to-video',
  },
  {
    id: 'hunyuan-image-to-video',
    name: 'Hunyuan I2V',
    provider: 'Tencent',
    tier: 'standard',
    badge: null,
    description: 'Tencent image-to-video with natural motion',
    creditCost: 12,
    type: 'image-to-video',
    maxDuration: 8,
    endpoint: '/hunyuan-image-to-video',
  },
  {
    id: 'vidu-i2v',
    name: 'Vidu 2.0 I2V',
    provider: 'Vidu',
    tier: 'standard',
    badge: null,
    description: 'Enhanced lighting, emotion dynamics, frame interpolation',
    creditCost: 12,
    type: 'image-to-video',
    maxDuration: 8,
    endpoint: '/vidu-i2v',
  },
  {
    id: 'runway-i2v',
    name: 'Runway Gen-3',
    provider: 'Runway',
    tier: 'premium',
    badge: null,
    description: 'Creative film-quality model for professional output',
    creditCost: 20,
    type: 'image-to-video',
    maxDuration: 10,
    endpoint: '/runway-i2v',
  },
  {
    id: 'grok-imagine-i2v',
    name: 'Grok I2V',
    provider: 'xAI',
    tier: 'standard',
    badge: 'NEW',
    description: 'Animate images — 6 to 30 seconds with ambient audio',
    creditCost: 18,
    type: 'image-to-video',
    maxDuration: 30,
    endpoint: '/grok-imagine-i2v',
  },
  {
    id: 'luma-modify-video',
    name: 'Luma Video Modify',
    provider: 'Luma',
    tier: 'standard',
    badge: null,
    description: 'Transform existing video — same motion, fresh look',
    creditCost: 15,
    type: 'video-to-video',
    endpoint: '/luma-modify-video',
  },
  {
    id: 'pixverse-v6-t2v',
    name: 'PixVerse v6',
    provider: 'PixVerse',
    tier: 'standard',
    badge: null,
    description: 'AI video generation with smooth motion and style control',
    creditCost: 12,
    type: 'text-to-video',
    maxDuration: 10,
    aspectRatios: ['16:9', '9:16', '1:1'],
    endpoint: '/pixverse-v6-t2v',
  },
  {
    id: 'ltx-2.3-text-to-video',
    name: 'LTX 2.3 T2V',
    provider: 'LightTricks',
    tier: 'standard',
    badge: null,
    description: 'Fast text-to-video generation with LTX quality',
    creditCost: 8,
    type: 'text-to-video',
    maxDuration: 8,
    aspectRatios: ['16:9', '9:16', '1:1'],
    endpoint: '/ltx-2.3-text-to-video',
  },
  {
    id: 'grok-imagine-extend',
    name: 'Grok Extend',
    provider: 'xAI',
    tier: 'standard',
    badge: 'NEW',
    description: 'Extend any video clip with AI-generated continuation',
    creditCost: 15,
    type: 'video-to-video',
    maxDuration: 30,
    aspectRatios: ['16:9', '9:16', '1:1'],
    endpoint: '/grok-imagine-extend',
  },
  {
    id: 'veo3.1-lite-text-to-video',
    name: 'Veo 3.1 Lite',
    provider: 'Google',
    tier: 'standard',
    badge: null,
    description: 'Faster, lighter version of Veo 3.1 — great quality, lower cost',
    creditCost: 15,
    type: 'text-to-video',
    maxDuration: 8,
    aspectRatios: ['16:9', '9:16', '1:1'],
    endpoint: '/veo3.1-lite-text-to-video',
  },
  {
    id: 'vidu-q3-turbo-text-to-video',
    name: 'Vidu Q3 Turbo',
    provider: 'Vidu',
    tier: 'standard',
    badge: null,
    description: 'Vidu turbo model — optimized for speed and quality',
    creditCost: 10,
    type: 'text-to-video',
    maxDuration: 8,
    aspectRatios: ['16:9', '9:16', '1:1'],
    endpoint: '/vidu-q3-turbo-text-to-video',
  },
  {
    id: 'vidu-q2-turbo-text-to-video',
    name: 'Vidu Q2 Turbo',
    provider: 'Vidu',
    tier: 'fast',
    badge: null,
    description: 'Vidu fastest tier — quick previews and rapid iteration',
    creditCost: 5,
    type: 'text-to-video',
    maxDuration: 6,
    aspectRatios: ['16:9', '9:16', '1:1'],
    endpoint: '/vidu-q2-turbo-text-to-video',
  },
]

export const LIPSYNC_MODELS = [
  {
    id: 'infinite-talk',
    name: 'Infinite Talk',
    provider: 'Muapi',
    tier: 'premium',
    badge: 'TOP',
    description: 'Portrait image to realistic talking video — fastest model',
    type: 'image-to-lipsync',
    endpoint: '/infinite-talk',
    creditCost: 8,
  },
  {
    id: 'ltx-lipsync',
    name: 'LTX 2.3 Lipsync',
    provider: 'LightTricks',
    tier: 'standard',
    badge: null,
    description: 'HD lipsync generation up to 1080p resolution',
    type: 'image-to-lipsync',
    endpoint: '/ltx-lipsync',
    creditCost: 6,
  },
  {
    id: 'latentsync',
    name: 'LatentSync',
    provider: 'Open Source',
    tier: 'standard',
    badge: null,
    description: 'Video-to-video lip sync from audio input',
    type: 'video-to-lipsync',
    endpoint: '/latentsync',
    creditCost: 5,
  },
  {
    id: 'wan2.2-speech-to-video',
    name: 'WAN 2.2 Speech',
    provider: 'Alibaba',
    tier: 'standard',
    badge: 'NEW',
    description: 'Speech-driven: image + audio = talking video',
    type: 'image-to-lipsync',
    endpoint: '/wan2.2-speech-to-video',
    creditCost: 10,
  },
  {
    id: 'muapi-lipsync',
    name: 'Muapi Lipsync',
    provider: 'Muapi',
    tier: 'standard',
    badge: null,
    description: 'Realistic lipsync — optimized for speed and quality',
    type: 'image-to-lipsync',
    endpoint: '/muapi-lipsync',
    creditCost: 4,
  },
]

export const AUDIO_MODELS = [
  {
    id: 'elevenlabs-tts',
    name: 'ElevenLabs',
    provider: 'ElevenLabs',
    tier: 'premium',
    badge: 'TOP',
    description: 'Gold standard for natural text-to-speech quality',
    type: 'text-to-voice',
    creditCost: 3,
  },
  {
    id: 'openai-tts',
    name: 'OpenAI TTS',
    provider: 'OpenAI',
    tier: 'standard',
    badge: null,
    description: 'Smooth, natural voice synthesis by OpenAI',
    type: 'text-to-voice',
    creditCost: 2,
  },
  {
    id: 'muapi-voice',
    name: 'Muapi Voice',
    provider: 'Muapi',
    tier: 'standard',
    badge: null,
    description: 'Fast multilingual TTS powered by Muapi',
    type: 'text-to-voice',
    creditCost: 1,
  },
  {
    id: 'suno',
    name: 'Suno',
    provider: 'Suno',
    tier: 'premium',
    badge: 'NEW',
    description: 'AI music generation — full songs in any genre',
    type: 'text-to-music',
    creditCost: 10,
  },
  {
    id: 'udio',
    name: 'Udio',
    provider: 'Udio',
    tier: 'standard',
    badge: null,
    description: 'Full AI music track creation with lyrics and style',
    type: 'text-to-music',
    creditCost: 8,
  },
  {
    id: 'mmaudio',
    name: 'mmAudio',
    provider: 'Muapi',
    tier: 'standard',
    badge: null,
    description: 'Synchronized synthetic speech and voiceover generation',
    type: 'text-to-audio',
    creditCost: 4,
  },
]

export function getModelsByType(type) {
  const all = [...IMAGE_MODELS, ...VIDEO_MODELS, ...LIPSYNC_MODELS, ...AUDIO_MODELS]
  return all.filter(m => m.type === type)
}

export function getModelById(id) {
  const all = [...IMAGE_MODELS, ...VIDEO_MODELS, ...LIPSYNC_MODELS, ...AUDIO_MODELS]
  return all.find(m => m.id === id)
}

// ===== Legacy exports for backward compatibility =====

// Model arrays
export const t2iModels = IMAGE_MODELS
export const i2iModels = IMAGE_MODELS.filter(m => m.type === 'image-to-image' || m.type === 'enhance')
export const t2vModels = VIDEO_MODELS.filter(m => m.type === 'text-to-video')
export const i2vModels = VIDEO_MODELS.filter(m => m.type === 'image-to-video')
export const v2vModels = VIDEO_MODELS.filter(m => m.type === 'video-to-video')
export const lipsyncModels = LIPSYNC_MODELS
export const imageLipSyncModels = LIPSYNC_MODELS.filter(m => m.type === 'image-to-lipsync')
export const videoLipSyncModels = LIPSYNC_MODELS.filter(m => m.type === 'video-to-lipsync')

// Legacy model getters
export function getImageModelById(id) { return IMAGE_MODELS.find(m => m.id === id) }
export function getVideoModelById(id) { return VIDEO_MODELS.find(m => m.id === id) }
export function getI2IModelById(id) { return i2iModels.find(m => m.id === id) }
export function getI2VModelById(id) { return i2vModels.find(m => m.id === id) }
export function getV2VModelById(id) { return v2vModels.find(m => m.id === id) }
export function getLipSyncModelById(id) { return LIPSYNC_MODELS.find(m => m.id === id) }

// Legacy helper functions — provide reasonable defaults
function getModelInputs(modelId, modelList) {
  const model = modelList.find(m => m.id === modelId)
  if (!model) return {}
  const tier = model.tier || 'standard'
  return {
    aspectRatios: model.aspectRatios || ['1:1', '16:9', '9:16', '4:3', '3:4'],
    resolutions: model.type?.includes('video') ? ['720p', '1080p'] : ['1K', '2K', '4K'],
    qualityField: model.type?.includes('video') ? 'quality' : 'resolution',
    maxImages: 4,
  }
}

export function getAspectRatiosForModel(modelId) { return getModelInputs(modelId, IMAGE_MODELS).aspectRatios }
export function getResolutionsForModel(modelId) { return getModelInputs(modelId, IMAGE_MODELS).resolutions }
export function getQualityFieldForModel(modelId) { return getModelInputs(modelId, IMAGE_MODELS).qualityField }
export function getAspectRatiosForI2IModel(modelId) { return getModelInputs(modelId, i2iModels).aspectRatios }
export function getResolutionsForI2IModel(modelId) { return getModelInputs(modelId, i2iModels).resolutions }
export function getQualityFieldForI2IModel(modelId) { return getModelInputs(modelId, i2iModels).qualityField }
export function getMaxImagesForI2IModel(modelId) { return getModelInputs(modelId, i2iModels).maxImages }
export function getAspectRatiosForI2VModel(modelId) { return getModelInputs(modelId, i2vModels).aspectRatios }
export function getResolutionsForI2VModel(modelId) { return getModelInputs(modelId, i2vModels).resolutions }
export function getDurationsForI2VModel(modelId) {
  const model = i2vModels.find(m => m.id === modelId)
  const base = [3, 5, 6, 7, 8]
  return model?.maxDuration && model.maxDuration > 8 ? [...base, Math.min(model.maxDuration, 30)] : base
}
export function getAspectRatiosForVideoModel(modelId) { return getModelInputs(modelId, t2vModels).aspectRatios }
export function getResolutionsForVideoModel(modelId) { return getModelInputs(modelId, t2vModels).resolutions }
export function getDurationsForModel(modelId) {
  const model = t2vModels.find(m => m.id === modelId)
  const base = [3, 5, 6, 7, 8]
  return model?.maxDuration && model.maxDuration > 8 ? [...base, Math.min(model.maxDuration, 30)] : base
}
export function getModesForModel(modelId) { return ['standard', 'pro'] }
export function getResolutionsForLipSyncModel(modelId) {
  const model = LIPSYNC_MODELS.find(m => m.id === modelId)
  return ['720p', '1080p']
}
